### ISSUE TITLE
Pas de TTS pour le nom du filtre si swipe "rapide"

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#21]
Si je swipe vite, le nom du filtre n'est pas verbalisé.

**Comment by lellex** [comment]
À tester si toujours d'actualité avec les dernières corrections apportées au menu

**Comment by GregIJA** [comment]
Pas reproduis je clos.
Tests uniquement fait sous Android 5.0.2.

**Comment by GregIJA** [comment]
En fait si y'a toujours ce problème.
Je suis en v0.0.14 sous Windows 10.
Si je swipe pendant qu'un TTS est lu, le nom du menu sur lequel je me place n'est pas vocalisé.

**Comment by mdartic** [comment]
Comportement attendu  :
- je suis sur un élément du menu
- j'entends le son de l'élément
- je swipe avant la fin de l'émission du son
- j'entends le son du nouvel élément

=> couper les sons en cours de lecture quand le lecteur joue un nouveau son
=> vérifier que le TTS / MP3 du svg marche aussi selon ce comportement

**Comment by mdartic** [comment]
@GregIJA à tester en https://github.com/makinacorpus/accessimap-lecteur-der/releases/tag/0.0.20 (build en cours)

**Comment by GregIJA** [comment]
Ne fonctionne pas sur les menus en 0.0.21.

**Comment by mdartic** [comment]
non reproduit à ce jour.
à tester par @GregIJA

**Comment by MedHediAmri** [comment]
Test version web:

-  Pas de TTS aussi dans le menu principal si on swipe rapidement

**Comment by MedHediAmri** [comment]
Test swipe rapide: Fonctionnement correct.
