### ISSUE TITLE
Implémentation des filtres incorrectes

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#23]
Mon cas d'usage est ma carte de Londres.

Je charge la carte de Londres (zip fourni en fichier attaché)
[Londres.zip](https://github.com/makinacorpus/accessimap-lecteur-der/files/539474/Londres.zip)
- le filtre Informations Générales est sélectionné par défaut : seules 2 interactions devraient être possible (1 sur le nom de la carte et une sur le nord)
  => ces deux interactions ne marchent pas et des interactions se lancent partout ailleurs (alors qu'elle ne devraient pas)
- si je sélectionne le Filtre Son, je n'arrive pas à activer BigBen
- si je sélectionne le Filtre Nom, tous mes POIs sont activables par simple clic (alors que le fichier xml indique du double clic). Je n'arrive pas à activer Madame Tussaud, le museum et d'autres POIs.

De façon générale les filtres ne sont pas bien implémentés. Rappel de ce que l'on attends:
Lorsque je sélectionne un filtre seuls les POIs associés sont sélectionnable et pour les activer je regarde l'action qui leur est associée dans le fichier interaction.

**Comment by lellex** [comment]
Ok pour le filtre "information générales", je vais l'ajouter.

Pour le reste, il ne s'agit pas d'un problème de filtres mais du document qui a été modifié avec Inkscape. De manière générale, tous les documents modifié avec Inkscape posent problème car des éléments peuvent être ajouté au dessus de ceux cliquable et donc empêché l'interaction.

**Comment by GregIJA** [comment]
Je ne suis pas certain que l'on parle de la même chose. Il faut clairement partir du principe qu'un document pourra être modifié en dehors du lecteur. On en discute aussi tout à l'heure.

**Comment by lellex** [comment]
Il pourra être modifié oui, c'est justement le rôle de l'éditeur. Mais je ne pourrais pas prendre en compte les modifs effectué sur un autre logiciel (Inkscape, Illustrator) ce serait beaucoup trop compliqué et dépendant de ce logiciel en question.

Si les ders doivent être modifiés, ce sera donc soit via l'éditeur, soit avec un logiciel tierce mais dans ce cas il faudra refaire une passe dans le code du svg pour "nettoyer" le document afin de ne pas écraser les actions.

**Comment by BastienAlvez** [comment]
- [ ] Implementation des filtres.
- [ ] Activation du poi en fonction de l'interaction associé

**Comment by GregIJA** [comment]
Tests sous Win10 / v0.0.19
OK
