### ISSUE TITLE
Problème de police braille

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#24]
L'écriture braille de la carte de Londres ne fonctionne pas.
![capture](https://cloud.githubusercontent.com/assets/12393758/19526665/68919c0c-9625-11e6-8a20-4223059ebe89.JPG)

**Comment by GregIJA** [comment]
Au dessus de London Map et en dessous de N on a normalement du braille.

**Comment by mdartic** [comment]
La police de braille à utiliser est disponible dans le repository de l'éditeur :

https://github.com/makinacorpus/accessimap-editeur-der/tree/master/app/assets/fonts

Fichier Braille_2007.ttf

**Comment by mdartic** [comment]
Police à installer, je ferme l'issue
