### ISSUE TITLE
Problème de TTS sous Win10

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#28]
Je suis en Français sous Win10 mais le TTS me parle anglais.
![capture](https://cloud.githubusercontent.com/assets/12393758/19527507/94688f04-9628-11e6-9af4-3793c8413ea2.JPG)

**Comment by lellex** [comment]
Je pense qu'il faut installer le package des voix. J'ai eu du mal à le trouver, voici ce que j'ai fait (mon système était totalement en anglais, la première étape n'est peut être pas nécessaire : 

**Étape 1**
- Paramètre de date, d'heure et régiaunaux supplémentaires (en bas de page sur le screenshot)
- Ajouter une langue
- Normalement là dans la langue français il doit y avoir un lien pour télécharger la langue

**Étape 2**
- Une fois téléchargée et installée, retourner dans le panneaux précédent (celui du screenshot)
- Aller dans "Voix"
- Il doit encore y avoir un bouton pour télécharger le pack de voix.

Peux-tu me dire si cela la voix français fonctionne après cela ?

**Comment by GregIJA** [comment]
Yep, c'est une procédure que je connais très bien je le fait régulièrement sur mes postes à l'IJA. En revanche j'ai compris pourquoi ça ne marchait pas : il y a un autre paramètre de synthèse vocale lorsque je vais sur Panneau de Configuration puis "Modifier les paramètres de la synthèse vocale". Et là j'étais sur Zira une voix US et j'ai pu changer ça en Hortense la voix française. Les mystères de Windows ...
![capture](https://cloud.githubusercontent.com/assets/12393758/19551469/989fbdb2-96ab-11e6-9f42-9ff0e1879de1.JPG)
