### ISSUE TITLE
Menu : comportement général

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#34]
Tests fait en v0.0.6
- [x] pour être homogène, si je clique sur Retour depuis le Menu principal on doit entendre "Fermeture du Menu"
- [x] dans les sous menus à choix (définir le document, choix du mode) l'item présélectionné doit être le dernier item qui a été choisi (même comportement que ce que j'ai décris dans les Filtres).
- [x] le menu "Changer le mode de lecture a un souci : premièrement il n'est pas vocalisé. 
- [x] deuxièmement je rentre dedans, clic sur retour puis je rentre à nouveau dedans : plus de focus sur aucun item. Le comportement souhaité est comme décrit dans le 2ème point de cette issue.

**Comment by lellex** [comment]
Sur la version 0.0.7, j'ai enlevé le menu "mode de lecture" car effectivement, je ne l'ai pas retravaillé et donc il ne fonctionne pas.

Il vaut mieux prioriser d'autres issues pour le moment : #24, #11 me paraissent plus prioritaires pour l'utilisation du lecteur.

Je remettrais ce menu dans une version ultérieure.

**Comment by GregIJA** [comment]
Android 5.0.2 Release 0.0.8
Le menu retour de "Changer de mode de lecture" ne marche pas.
Est-ce que les actions de ce menu ont été implémentées?
Je propose pour le moment de l'enlever, ce menu n'est pas du tout prioritaire. Il faut que le reste fonctionne bien avant de passer à ça.

**Comment by lellex** [comment]
J'ai enlevé le menu "Changer le mode de lecture" car effectivement on a laissé de côté le mode de recherche.

J'ai aussi retiré le menu "Définir le document à visualiser" car il me semble qu'il n'était pas utile non plus. Un document finalisé ne devrait contenir qu'un seul xml (à voir en fonction de l'éditeur si on doit quand même embarquer les sources ?).

Tout ça devrait donc régler les problème de menu vu qu'il ne reste plus que le calibrage et les filtres. À tester.
