### ISSUE TITLE
Menu et Filtres : première item non clicable

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#35]
Test fait en v0.0.6
Je ne peux pas cliquer sur le premier item des menus Filtres et Menu : il faut que je clic en dehors de l'item pour faire marcher le clic et/ou le double-clic. Pour les autres item le comportement est correct.

**Comment by lellex** [comment]
Je ne comprends pas ce bug, chez moi le double click et le click fonctionne sur le 1er item (bien que l'action derrière soit encore à améliorer, cf. les filtres..).

Peux-tu détailler la démarche pour reproduire ce bug ?

**Comment by GregIJA** [comment]
![capture](https://cloud.githubusercontent.com/assets/12393758/19693112/ae2ad54e-9ada-11e6-8b3b-91f31f69635c.JPG)

Yep, si je clic ou double clic sur la zone en rouge chez moi ça ne marche pas (win10 64 bits).

**Comment by lellex** [comment]
Ah oui je n'avais pas tester avec cette taille d'écran (normalement si la fenêtre est assez grande le menu est à droite donc pas le problème).
