### ISSUE TITLE
Si j'importe un DER avec un seul élément interactif, le DER ne se charge pas

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-lecteur-der#36]
Le lecteur attend un 'tableau de pois', alors qu'il n'y en a qu'un.

**Comment by lellex** [comment]
Il me semble que c'est résolu ?
Testé avec [SingleObject](https://github.com/makinacorpus/accessimap-lecteur-der/blob/master/cordova/www/der/SingleObject.zip).

**Comment by mdartic** [comment]
Exact
