### ISSUE TITLE
Chargement d'un document

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#43]
Tests réalisés sous Android 5.0.2, Release 0.0.8.
Lorsque je charge un document : 
- le menu "Menu" reste à l'état "Fermer" : devrait redevenir Menu puisqu'on le quitte.
- pour savoir que la carte a bien était chargée il faut prévoir un feedback audio ("Document correctement chargé" et "Erreur lors du chargement du document".
- si le document pose des problèmes il ne faut pas fermer le menu.

**Comment by mdartic** [comment]
à re tester en 0.0.24

**Comment by GregIJA** [comment]
0.0.27
Sur Android, je n'arrive plus à rentrer dans le menu.
