### ISSUE TITLE
Problème chargement de document

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#44]
Android 5.0.2, Release 0.0.8
J'ouvre le Menu.
Je vais dans le menu choix des documents.
Je fais Retour puis Retour.
J'ai un message "Fichier, non valide, aucun document ...".

**Comment by mdartic** [comment]
Logiquement, pas mal de soucis ont été réglés, mais pour pouvoir ouvrir un document, je te propose d'utiliser un Google Drive pour uploader tes zips de dessins, puis ensuite de les ouvrir à travers le lecteur sur Android.

**Comment by GregIJA** [comment]
Ce menu n'existe plus, on clos.
