### ISSUE TITLE
A l'ouverture de l'application, pas de carte préchargée par défaut.

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#45]
Tout est dans le titre.

**Comment by mdartic** [comment]
Presque,
Tu veux qu'il y en ait une, ou tu ne veux pas qu'il y en ait ?

**Comment by GregIJA** [comment]
Pardon c'est pas très clair : il n'en faut pas.
Je pense que Londres c'est uniquement pour vos tests!

**Comment by mdartic** [comment]
vrai :-)
