### ISSUE TITLE
Renommer l'application Androir en Mapsense plutôt que HelloCordova.

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#47]

**Comment by lellex** [comment]
J'avais renommé l'application avant de voir ce ticket. Je l'ai nommé Lecteur Accessimap. C'est Mapsense plutôt ? Y a-t-il un logo ou on pourra utiliser celui d'Accessimap ?

**Comment by GregIJA** [comment]
De préférence Mapsense pour le moment :)
Accessimap c'est le projet ANR ça englobe bien plus que le lecteur / éditeur de DER.
On utiliser le logo d'accessimap on verra plus tard pour un logo spécifique.

**Comment by GregIJA** [comment]
ok
