### ISSUE TITLE
Intégrer le tag de release dans les noms de fichiers générés par le build Travis

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-lecteur-der#48]
Actuellement, bloqué en 0.0.8, et nous en sommes à la 0.0.12.

**Comment by lellex** [comment]
Le numéro de version a été ajouté à Travis via $TRAVIS_TAG 
cf. https://github.com/makinacorpus/accessimap-lecteur-der/releases/tag/0.0.15
