### ISSUE TITLE
Rendre le zoom inactif

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#57]
Test effectué sous Windows / v0.019
On ne doit pas pouvoir zoomer l'application.

**Comment by mdartic** [comment]
à voir avec https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

**Comment by mdartic** [comment]
et https://msdn.microsoft.com/en-us/library/windows/apps/hh767313.aspx

**Comment by MedHediAmri** [comment]
Test version web:

- Zoom inactif.
