### ISSUE TITLE
Problème de build

### ISSUE THREAD

**Issue by lellex** [makinacorpus/accessimap-lecteur-der#59]
Visiblement travis n'arrive plus à builder depuis la mise à jour d'electron ?

**Comment by mdartic** [comment]
Mmm pas exactement...

Le fichier est généré mais non transféré.⁣ Le build semble ok mais les artefacts ne sont pas transférés?

Je regarde plus en détails...

Le 4 avr. 2017 18:43, à 18:43, Alexandra J <notifications@github.com> a écrit:

**Comment by mdartic** [comment]
ok, fixé avec la release https://github.com/makinacorpus/accessimap-lecteur-der/releases/tag/0.0.23

il y avait un souci par rapport aux versions des différents packages, il fallait bumper à chaque fois.

ce qui a amené à un décalage à moment donné, car j'ai oublié de monter les versions.

désormais, tous les fichiers présents dans electron/dist/accessimap* sont remontés, ainsi que les *.apk .

il faudra sûrement retravailler le nommage des builds electron & android pour qu'ils s'appellent correctement, et intègrent le n° de la release, et pas forcément le semver npm ?
que penses tu de cette dernière proposition ?
