### ISSUE TITLE
Bouton retour

### ISSUE THREAD

**Issue by lellex** [makinacorpus/accessimap-lecteur-der#6]
Lorsque un menu est ouvert (filtres ou menu de droite), il se transforme en bouton "Retour".
Le bouton du menu qui n'est pas active ne doit plus être visible. (= si le menu principal est ouvert, le menu filtre n'est pas affiché)

**Comment by GregIJA** [comment]
On discutera de la meilleure manière de faire, on va dire qu'on attends des input avant de décider (Bernard).
