### ISSUE TITLE
Calibration : quelques améliorations

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#64]
Il n'est pas utile de proposer les différentes tailles puisqu'elles ne correspondent jamais au bon format.
Je propose de simplifier : quand un clic sur Calibrer on a directement l'écran de calibration.
Autre chose, au lancement de l'écran de calibration le "Menu" devient "Enregistrer" et non "Fermer".
Car on est bien d'accord que cette taille est enregistrée et donc conservée pour les fois suivantes?

**Comment by mdartic** [comment]
vu avec @GregIJA 

on garde les différents types de calibrage, A5 / A4 / A3 pour l'instant, par contre ok pour les boutons

et oui, la taille est enregistrée dans le localStorage du navigateur, donc conservée pour les fois suivantes

**Comment by MedHediAmri** [comment]
Test version web:
- Au lancement de l'écran de calibration le "Menu" devient "Fermer pas "enregistrer".
