### ISSUE TITLE
Bip à la fermeture des filtres ou du menu?

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#66]
0.0.27 Windows 10 64 bits
Pourquoi un bip à la fermeture des filtres ou du menu? 
On a l'impression que le document est rechargé à chaque fois.
Normalement je dois entendre plutôt fermeture du menu ou fermeture des filtres ce qui est le cas de temps en temps (à mon avis c'est toujours le problème de pouvoir couper le TTS en cours).

**Comment by MedHediAmri** [comment]
Test version web:

- Bip encore actif lors de la fermeture des filtres ou menu.

**Comment by MedHediAmri** [comment]
Test de la version 032: Bip encore actif.

**Comment by MedHediAmri** [comment]
Test de la version 034. Bip supprimé.
