### ISSUE TITLE
Vocalisation de l'item courant dans Filtres et Menu

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#67]
0.0.27 Windows 64 bits
Lorsque j'ouvre le menu ou les filtres le nom de l'item courant n'est pas toujours vocalisé (et quand il l'est il attend 1 ou 2 secondes avant de parler).
Il me semblait avoir déjà ouvert une issue la dessus que je ne retrouve pas.

**Comment by MedHediAmri** [comment]
Test version web:
Les items des menus "Menu" et "Filtres" sont vocalisés.
