### ISSUE TITLE
"Fermer le menu" ou "Femer les filtres" n'est vocalisé de temps en temps

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#69]
WIndows 10 x64
à mon avis cf #21

**Comment by MedHediAmri** [comment]
Test version web
- "Fermeture du menu" est vocalisé.

**Comment by MedHediAmri** [comment]
Test: Fermeture de filtres ou du menu n'est pas du tout vocalisé.

**Comment by MedHediAmri** [comment]
Test de la version 034. Fermeture de filtres ou du menu est vocalisée.
