### ISSUE TITLE
Chargement de document parfois ne marche pas 

### ISSUE THREAD

**Issue by GregIJA** [makinacorpus/accessimap-lecteur-der#70]
0.0.27 Windows 10 x64
C'est le genre d'issue que l'on déteste mais je n'ai pas de scénario type.

Parfois au chargement j'ai un sablier qui tourne dans le vide : obligé de faire un ctrl alt suppr.

**Comment by mdartic** [comment]
non reproduit à ce jour, on laisse ouvert au cas où on trouve un cas d'utilisation.

**Comment by MedHediAmri** [comment]
Test version web (chrome):

- Chargement de document fonctionne correctement.
