### ISSUE TITLE
Ne pas dire 'Ouverture du menu' lors de l'ouverture du menu

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-lecteur-der#72]

**Comment by mdartic** [comment]
@GregIJA idem que #74

**Comment by MedHediAmri** [comment]
Test version web:

-  Lors de l'ouverture du menu principal, le message vocal est: "Ouverture du menu"

**Comment by MedHediAmri** [comment]
Test effectué: ça fonctionne correctement.
