### ISSUE TITLE
Améliorer fonctionnement menu

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-lecteur-der#74]
Le fonctionnement dans tous les Menus et Sous Menus doit être le suivant :

- simple clic = je vocalise l'item courant (ça ca marche)
- double clic = je vocalise uniquement l'item courant du menu dans lequel j'entre 
  - si je double clic sur Menu il y a un TTS "Menu" : NOK on voudrait directement l'item courant (idem pour Filtre)
  - si je double clic sur Calibrer l'écran il y a un TTS "Calibrer" et rien d'autre : NOK on ne veut pas de "Calibrer" et on veut directement l'item courant
-  retour depuis le menu principal ou filtre => ne rien vocaliser, directement le "bip" : OK pour Menu, NOK pour Filtres
- retour depuis "Calibrer" (ou tout autre futur sous menu) : je remonte dans le menu parent et je vocalise l'item courant: NOK : toujours pareil on ne veut pas de "Retour" mais juste avoir en audio le nom de l'item courant du menu principal (soit "Calibrer" car je viens de ce sous menu).

**Comment by mdartic** [comment]
@GregIJA ça me paraît ok

tu px tester sur http://makinacorpus.github.io/accessimap-lecteur-der/#/?

**Comment by GregIJA** [comment]
Ok.
