### ISSUE TITLE
Désactiver le zoom du lecteur sous Chrome / Electron / Cordova

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-lecteur-der#76]
Suite à essais hier par Bernard lors de l'inauguration, le zoom est actif sous Chrome sous Windows.

=> le désactiver.

Vérifier qu'il en est de même sous Electron / Cordova.

**Comment by mdartic** [comment]
A tester aussi avec https://superuser.com/questions/1081099/disable-pinch-zoom-gesture-in-chrome-windows-10

**Comment by lellex** [comment]
Les solutions proposées ne donnent rien...
J'ai trouvé ça aussi https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Multi-touch_interaction

**Comment by lellex** [comment]
Ok sur chrome. Reste à tester avec electron et cordova

**Comment by MedHediAmri** [comment]
Test version web:

- Sous chrome le zoom est désactivé.
