### ISSUE TITLE
Rendre possible le double-tap avec un écran multi-points

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-lecteur-der#77]
Lors de l'utilisation du lecteur sous Windows & l'écran multi-points (10 points), le double-tap n'est pas déclenché lorsque plus d'un doigt est en contact avec l'écran.

Par ex : j'ai un doigt qui découvre le dessin, un deuxième qui fait un double-tap sur un élément interactif : rien ne se passe. Vrai avec 9 doigts + 1 dixième qui lance l'interaction.

=> trouver une solution pour permettre le double tap dans ces conditions d'utilisation.

**Comment by GregIJA** [comment]
C'est "pire" que ça : le double tap ne se déclenche pas à partir du moment ou un seul autre doigt est en contact.

**Comment by mdartic** [comment]
Exact, je modifie un peu le contenu.

**Comment by mdartic** [comment]
Sur MapSense, cela marchait ? Tu avais dû gérer un truc en particulier ?

**Comment by GregIJA** [comment]
Yes ça marche jusqu'à 9 doigts : non rien eu à faire, l'API multi-touch faisait le boulot.
