### ISSUE TITLE
Empêcher d'avoir 2 sons lancés en même temps

### ISSUE THREAD

**Issue by lellex** [makinacorpus/accessimap-lecteur-der#81]
Dans le cas d'un der contenant des mp3, si on clique plusieurs fois dessus, le son se lance plusieurs fois.

**Comment by MedHediAmri** [comment]
Test fait avec un der contenant TTS. Fonctionnement correct. Il y a déjà un problème pour pouvoir réaliser un DER avec des sons MP3. Une fois c'est réglé je reviens tester cette issue.

**Comment by mdartic** [comment]
Tu peux tester avec ce der de Londres qui contient exclusivement des sons mp3.

[Londres.zip](https://github.com/makinacorpus/accessimap-lecteur-der/files/1421635/Londres.zip)

**Comment by MedHediAmri** [comment]
test effectué avec la version 0.32. Fonctionnement correct.
