### ISSUE TITLE
Permettre d'utiliser le lecteur à la souris

### ISSUE THREAD

**Issue by lellex** [makinacorpus/accessimap-lecteur-der#82]
Lors des derniers développements, afin de corriger le problème de click avec plusieurs doigts posés sur l'écran, nous avons été contraint de ne plus pouvoir utiliser le lecteur à la souris (seulement au touch via un écran tactile).

Cependant, il reste utilisable via chrome si on active le mode émulation de device en choisissant un device tactile.

Côté technique : les énévénements click/dbclick sont remplacés par un service qui écoute le `touchstart`. cf. modules/der-reader/src/services/touchevents.js. Si on écoute aussi le clique ou le `mousedown`, l'événement est joué 2 fois.

**Comment by MedHediAmri** [comment]
Test de la dernière version web:

- On ne peut pas pas choisir le menu "Menu" avec la souris. Contraint d'entrer dans le menu avec l'écran tactile pour tester les autres menus.

- En mode souris on peut effectuer le chargement de document relief donc OK

- On n'a pas réussi à sélectionner les autres menus ("Calibrer l'écran", "Quitter l'application" et "Retour") avec simple clique mais on doit rester maintenir clique gauche et faire une translation main maintenue sur la souris. Cela ne fonctionne pas à tous les coups.

- Une fois les menus  ("Calibrer l'écran", "Quitter l'application" et "Retour") sont sélectionnés, on ne peut pas les activer en mode souris.

**Comment by MedHediAmri** [comment]
Fonctionnement correct avec la souris.
