### ISSUE TITLE
Chargement document ne fonctionne pas dans la version 0.29

### ISSUE THREAD

**Issue by MedHediAmri** [makinacorpus/accessimap-lecteur-der#83]
J'utilise Windows 10 et Chrome 2017 (version: 60.0.3112.113). Il y a un bug au niveau du lecteur DER version 0.29 : Le chargement de cartes ne fonctionne pas : La boite de dialogue Windows pour sélectionner le document n’apparaît pas.

**Comment by MMace31** [comment]
On l'a cherché derrière, sur l'autre écran. Elle semble ne pas être appelée correctement.

**Comment by mdartic** [comment]
Quand tu dis 'sur l'autre écran', qu'est ce que cela veut dire ? Vous fonctionnez en double écran ?
Notre configuration nominale est : un PC + un écran tactile.
Nous n'avons pas de double écran.

**Comment by MMace31** [comment]
On a re-testé : avec 1 écran ou 2 écrans (Iiyama en écran primaire), c'est pareil : la boite de dialogue pour choisir un document ne s'affiche pas. Une fois "charger un document" validé, le Menu reste sur "Fermer", on peut double taper dessus pour qu'il affiche "menu", puis double taper à nouveau pour qu'il affiche le menu. Mais on ne voit jamais la boîte de dialogue. Et elle n'est pas en dehors de l'écran, je ne la trouve pas en alt+espace pour essayer de la déplacer. On a aussi ré-initialisé les paramètres dans Roaming.

Je pense vraiment que c'est un mini-bug qui a été introduit sur la fin, juste avant le release.

**Comment by MedHediAmri** [comment]
Merci. Test effectué avec la version web: la boite de dialogue s'ouvre.

**Comment by mdartic** [comment]
Merci, j'ai pushé le chargement du der.
La version web est à jour.
Nota Bene : l'ouverture du menu de chargement des fichiers s'effectue par simple tap. 

Je pose néanmoins la question ici, pour @GregIJA et @MMace31 : 
A t'on besoin réellement d'un menu qui gère le swipe / double tap ? 
Pour la version web et la version desktop, je me pose la question.
Pour la version smartphone / tablette, pourquoi pas.
Dans ce dernier cas, on pourrait s'appuyer sur les compétences natives des OS en matière d'accessibilité et de gestion tactile.

**Comment by GregIJA** [comment]
Yop,
Quelque soit le device le lecteur est une appli faite pour le tactile. A partir de là les interactions classiques en mode lecteur d'écran pour la navigation d'un menu c'est le swipe pour parcourir les items et le double tap pour la sélection. Je sais pas si je répond à côté de ta question :)

**Comment by GregIJA** [comment]
Ce qui ne contredit pas ta dernière phrase.

**Comment by mdartic** [comment]
Moui :-) 
Je reste encore sur ma faim.

**Comment by MMace31** [comment]
- On va tester ça de suite.

- Pour tes questions 
   - Sur tablette, si talkback/voiceover est activé, tu n'as plus accès aux événements tactiles, donc il faut gérer le swipe et dble tap.
   - Sur Windows, il faut tester avec le narrateur, mais entre Jaws/NVDA/Narrateur activé ou pas, ça complique pas mal la question. Le plus simple c'est quand même peut être le comportement actuel (swipe et dble tap géré par vous). Qu'est-ce qui fait qu'il serait mieux de changer ça ?

**Comment by mdartic** [comment]
Merci pour les réponses.
Le constat est que nous tordons le cou au web tel que nous le connaissons, qui est du web théoriquement 'hyper lien', en le rendant applicatif avec la gestion du swipe & co.
Rien de bien étrange à vrai dire, mais nous rencontrons une difficulté pour ouvrir une boîte de dialogue qui habituellement est un champ texte avec un bouton juxtaposé.
Nous changeons les mécaniques, et de fait nous avons pris un 'avertissement' par la mise à jour de Chrome qui interdit nos façons de faire. (pour des raisons de sécurité)
Cela me fait donc réfléchir, et c'est pour cela que je vous soumets la question, car n'ayant pas été au début des discussions sur le lecteur, je n'avais pas les raisons de ces choix.

A ce jour, nous pouvons peut être nous satisfaire du comportement actuel (à vous de nous dire).

**Comment by MedHediAmri** [comment]
Test version web:

- Chargement du document DER effectué avec succès  

- Menu stable (ne translate pas)

- Zoom-Dezoom désactivé

- Filtres: fonctionnement correct

- Calibration rectifiée avec un seuil minimal sans risque de perdre le menu

- Balayage avec dix doigts puis tap ou double tap (9 doigts restent sur l'écran): fonctionnement normal de l'interaction

**Comment by mdartic** [comment]
Pas mal donc ?

**Comment by MedHediAmri** [comment]
Oui le chargement de document s'effectue bien. Je ferme donc cette issue et je passe aux autres.
