### ISSUE TITLE
Problème texture des formes géométriques dans le lecteur DER version 0.28

### ISSUE THREAD

**Issue by MedHediAmri** [makinacorpus/accessimap-lecteur-der#84]
Lors du test du lecteur DER version 0.28, dans la carte que j'ai essayé j'ai mis des formes géométriques avec des texture (hachures). Lors de l'interaction (tap et double tap) les textures changent.

**Comment by mdartic** [comment]
Peux tu nous fournir ta carte pour reproduire l'anomalie ?

**Comment by MedHediAmri** [comment]
[Carte des bâtiments historiques.zip](https://github.com/makinacorpus/accessimap-lecteur-der/files/1362140/Carte.des.batiments.historiques.zip)

**Comment by mdartic** [comment]
Pour préciser ce que tu as constaté, peux tu me confirmer que : 
* lorsque tu cliques sur une forme géométrique qui est affichée en rectangle rouge + hachure droite
* les hachures disparaissent lors du jeu de l'interaction
* puis elles reviennent une fois l'interaction terminée

Si tu avais mis une forme géométrique sur fond bleu, elle serait devenue à fond rouge, car c'est la forme identifiée pour rendre 'visible' l'interaction courante.

Si tu as d'autres propositions, pourquoi pas, mais je ne suis pas sûr que ce soit gênant en l'état.

**Comment by MedHediAmri** [comment]
C'est bon merci. Je ferme l'issue.
