### ISSUE TITLE
Windows détecte le lecteur DER comme source inconnue

### ISSUE THREAD

**Issue by MedHediAmri** [makinacorpus/accessimap-lecteur-der#85]
J'utilise Windows 10 et Chrome 2017 (version: 60.0.3112.113). Lors du lancement du lecteur DER (version 0.29), Windows a détecté l'application comme source inconnue

**Comment by MMace31** [comment]
Ca ne se produit qu'une fois au lancement de l'appli. C'est pas une priorité
