### ISSUE TITLE
Interface du lecteur version 0.29 bouge

### ISSUE THREAD

**Issue by MedHediAmri** [makinacorpus/accessimap-lecteur-der#86]
J'utilise Windows 10 et Chrome 2017 (version: 60.0.3112.113). Il y a un bug au niveau du lecteur DER version 0.29: L'interface initiale là où il y a "Menu" et "Fermer" bouge ( se translate) lorsqu'on fait un swap.

**Comment by MMace31** [comment]
Elle se déplace très peu, d'environ 1/2 cm, verticalement

**Comment by MMace31** [comment]
C'est good 👍
