### ISSUE TITLE
Problème calibration du lecteur DER version 0.29

### ISSUE THREAD

**Issue by MedHediAmri** [makinacorpus/accessimap-lecteur-der#87]
J'utilise Windows 10 et Chrome 2017 (version: 60.0.3112.113). Il y a un bug au niveau du lecteur DER version 0.29: Lors de la calibration, fausse manœuvre avec les doigts est prise en compte. La calibration est effectuée pour une taille trop petite. Il vaut mieux fixer une taille minimale au dessous de laquelle on ne fait pas la calibration.

**Comment by MMace31** [comment]
C'est très ennuyeux parce qu'on ne peut plus sortir de la calibration ou du programme et que ce paramètre n'est pas stocké dans le dossier du programme mais dans le profil utilisateur Windows. Il faut aller supprimer des fichiers de config du lecteur pour retrouver un lecteur fonctionnel.

**Comment by mdartic** [comment]
Pouvez vous préciser le mode opératoire précisémment ?
Le lecteur ne peut en effet pas détecter que la manoeuvre est erronée.
Une taille minimale est délicate à fixer, car les problèmes de pixels sont assez complexes.
Ce qui est étrange, c'est que tant que le calibrage n'est pas validé, l'utilisateur peut poursuivre la calibration ? Si cela ne marche pas, merci de nous le signaler.

**Comment by MMace31** [comment]
Alors, c'est tout simple, si tu lance la calib et que tu clique par inadvertance très proche de l'origine, puis double-tap sur fermer, qui est est le seul label visible du menu déroulant. Ca te valide la calib et impossible de changer cette calibration erronée puisque le menu ne tient plus dans la fenêtre.
Ca confirme : mettre une taille mini de calibration qui fait qu'on a encore accès aux options du menu déroulant.

**Comment by mdartic** [comment]
J'ai fixé la limite à 300px.
Merci de me dire si c'est suffisant ou pas. (sachant que les 300px sont à un pixel ratio potentiellement aléatoire)

**Comment by MMace31** [comment]
Yep, c'est bon là. Je ferme.
