### ISSUE TITLE
Pas d'interaction quand on mets plusieurs doigts sur l'écran

### ISSUE THREAD

**Issue by MedHediAmri** [makinacorpus/accessimap-lecteur-der#90]
Test version 0.32.
Quand on balaye l'écran avec plusieurs doigts et qu'on tape sur un objet, il n'y a pas d’interactions. Le filtre ne répond pas. Par exemple, si je laisse un ou plusieurs doigts sur l'écran et que j'active avec un seul doigt un objet ça ne marche pas.

**Comment by mdartic** [comment]
Entendu, il y a sûrement eu régression dans les événements avec la gestion du click... 
Je regarde ça.

**Comment by MedHediAmri** [comment]
Test de la version 0.33. Bug résolu.
