### ISSUE TITLE
Chargement DER avec la version 0.34

### ISSUE THREAD

**Issue by MedHediAmri** [makinacorpus/accessimap-lecteur-der#94]
J'ai fait un test du lecteur version 0.34 et la version web. Je lance l'application.

- Pour ouvrir un nouveau document, une première boite de dialogue s'affiche pour que je choisisse le DER. Je valide mon choix. Une deuxième boite de dialogue s'ouvre pour que je refasse le même choix.

- Si je veux changer de DER je vais au menu pour charger un nouveau document. Je valide mon choix.  Le document n'est pas chargé mais le document que j'ai chargé au début demeure affiché. Il fallait que je quitte carrément l'application et que je la relance pour charger le document que je souhaite.

**Comment by mdartic** [comment]
Bug reproduit pour le changement de DER.
Par contre, je n'ai pas réussi à reproduire sur le premier point.
On a dû faire des concessions sur ce chargement de document suite à un changement dans Chrome récemment cf #83.
Est ce que tu fais un double tap sur l'item 'Charger un nouveau document en relief', ou un simple tap ?
En l'occurrence, un simple tap suffit.

**Comment by MedHediAmri** [comment]
D'accord. Effectivement je faisais un double tap. Avec le simple tap ça fonctionne correctement mais je pense qu'il faut gérer au cas où on fait double tap. 
Par contre, quand je veux charger de DER je n'arrive pas., ça reste bloqué au premier document que j'ai chargé. Je suis obligé de quitter carrément l'application pour charger le document que je souhaite explorer.

**Comment by mdartic** [comment]
Oui, affirmatif pour le premier document bloqué... je regarde ça en ce moment même.
Pour le double tap, ce n'est clairement pas possible techniquement : bloqué par Google.
Et je ne crois pas qu'un déficient puisse être autonome sur le chargement d'un DER.
Ce que j'aurais tendance à proposer passe plutôt par une reprise de ce menu, avec une option de paramétrage du lecteur, dans lequel un non déficient pourrait ajouter plusieurs DERi, et ceux là deviendraient accessible au déficient via un menu 'Sélection du document en relief'.
Là ça marcherait avec du double tap.
Qu'en penses tu ?

**Comment by MedHediAmri** [comment]
D'accord. J'ai utilisé la nouvelle version en ligne pour créer un nouveau document. L'ajout d'une double interaction pour un même filtre est clair. Par contre je n'ai pas pu exporter le document. La procédure se lance mais ça plante.

**Comment by MedHediAmri** [comment]
Test effectué. Fonctionnement correct.
