### ISSUE TITLE
Anomalie avec la gestion du click / touch

### ISSUE THREAD

**Issue by mdartic** [makinacorpus/accessimap-lecteur-der#95]
Suite à la remise en place de la gestion du clic souris en supplément du touch de l'écran tactile.
Lorsque l'on commence à utiliser l'écran, la souris n'est plus reconnue.
Inversement, si j'utilise la souris au début, l'écran fonctionne.

Cela est lié au fait que l'écran transmet à la fois du Touch et du MouseEvent.
Néanmoins, il y a une anomalie.

**Comment by MedHediAmri** [comment]
Test effectué. La souris est reconnue. Fonctionnement correct.
